# 파일 규격 버전
version: "3"

networks:
  3pdx-bridge: #원하는 네트워크 명으로 변경 가능
    external: true


# 실행하려는 컨테이너들 정의
services:
  # 서비스명
  redis:
    # 사용할 이미지
    image: taehoony/redis:1.0
    # 컨테이너명
    container_name: redis_3pdx
    hostname: redis
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    ports:
      - 55426:6379
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료시 재시작 여부 설정
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      3pdx-bridge:
        ipv4_address: 172.23.0.4
